"""Add is_owner column to room_user

Revision ID: 021502f16780
Revises: ae34fd2e0a87
Create Date: 2024-01-17 21:48:39.354516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '021502f16780'
down_revision: Union[str, None] = 'ae34fd2e0a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_user', sa.Column('is_owner', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_user', 'is_owner')
    # ### end Alembic commands ###
