"""Create database(1)

Revision ID: cf3f0aa2b06e
Revises: 9e0bdeeaae69
Create Date: 2024-01-17 21:28:17.964607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3f0aa2b06e'
down_revision: Union[str, None] = '9e0bdeeaae69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
