"""Update database

Revision ID: f060b09b8a51
Revises: 64b4815c94c6
Create Date: 2024-01-18 19:34:06.903566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f060b09b8a51'
down_revision: Union[str, None] = '64b4815c94c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'message_data',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'message_data',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
    # ### end Alembic commands ###
