"""Database update

Revision ID: fd6ecead011c
Revises: 9a39f1d60a84
Create Date: 2023-12-01 09:03:25.475568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6ecead011c'
down_revision: Union[str, None] = '9a39f1d60a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_user', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.create_unique_constraint('uq_user_room', 'room_user', ['user', 'room'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_room', 'room_user', type_='unique')
    op.drop_column('room_user', 'update_date')
    # ### end Alembic commands ###
